### ISSUE TITLE
EZYFOX_SERVER_HOME

### ISSUE THREAD

**Issue by erharut** [youngmonkeys/ezyfox-server#10]
Hi, 
In pom.xml 
<deploy.path>${env.EZYFOX_SERVER_HOME}</deploy.path>
cannot resolve symbol env.EZYFOX_SERVER_HOME, 
how can fix this?

thanks in advance.

**Comment by tvd12** [comment]
what is your operating system?

**Comment by erharut** [comment]
Windows 10 64x

**Comment by tvd12** [comment]
[ezyfox-server-nio.zip](https://github.com/youngmonkeys/ezyfox-server/files/1504960/ezyfox-server-nio.zip)
1. Let's download zip file
2. Follow this [tutorial](https://www.computerhope.com/issues/ch000549.htm) to add the variable `EZYFOX_SERVER_HOME` to your system

**Comment by tvd12** [comment]
please let me know when you finish, I'll close this issue

**Comment by erharut** [comment]
Thanks
