### ISSUE TITLE
Support Docker Build

### ISSUE THREAD

**Issue by trungdlp-wolffun** [youngmonkeys/ezyfox-server#118]
**Is your feature request related to a problem? Please describe.**
Developers currently face challenges while setting up the development environment for the project. There are multiple dependencies, and the setup process can be time-consuming and error-prone, especially when working on different platforms or operating systems. This complexity hinders the onboarding of new contributors and slows down the development process.

**Describe the solution you'd like**
I propose adding a Dockerfile to the project's repository. The Dockerfile will define a containerized development environment with all the necessary dependencies and configurations to run the project seamlessly. By using Docker, developers can easily set up a consistent environment across different platforms, avoiding the hassles of dealing with dependencies manually.

**Describe alternatives you've considered**
1. Manual Setup: Developers could continue setting up their development environment manually, but this approach is prone to errors and can lead to inconsistencies across different setups.
2. Virtual Environments: Some developers might choose to use virtual environments, but this still requires installing and managing dependencies on the host system, leading to potential conflicts and difficulties in reproducing the same environment elsewhere.

**Additional context**
Adding a Dockerfile will not only simplify the development setup but also streamline the continuous integration and deployment processes. Developers will be able to use Docker-compose to manage complex setups with ease, further enhancing the project's development experience. Additionally, the Dockerfile can be accompanied by clear documentation on how to use it, making it accessible to both experienced and new contributors.

By adopting Docker, we can significantly improve the development workflow and foster a more collaborative and efficient development community around the project.

Thank you for considering this feature request. If there are any questions or suggestions, please feel free to ask or provide feedback.

**Comment by tvd12** [comment]
@trungdlp-wolffun pls put more details

**Comment by trungdlp-wolffun** [comment]
@tvd12, thank you for your feedback. I appreciate the opportunity to provide more details regarding the feature request.

The proposed Dockerfile aims to simplify the development setup process for the project. It will define a containerized development environment with all the necessary dependencies and configurations, ensuring a consistent and reproducible development environment across different platforms.

By using Docker, developers can quickly set up the project without worrying about manual dependency installations, version conflicts, or platform-specific issues. This will facilitate smoother onboarding for new contributors and reduce the chances of development hiccups due to environment inconsistencies.

Additionally, the Dockerfile will enable better integration with continuous integration and deployment workflows, making it easier to maintain and deploy the project in various environments.

If there are specific aspects you'd like me to elaborate on or any other questions you have, please let me know. I'm more than happy to provide further information to support this feature request.

Thank you again for your attention to this matter.

**Comment by tvd12** [comment]
@trungdlp-wolffun ezyfox-server is a framework, not a product, so add a docker file to ezyfox server repo doesn't make meaning. So:

You can contribute to [ezyfox server archetype](https://github.com/youngmonkeys/ezyfox-server-archetype) it's a maven archetype, provide a template for project that use ezyfox server. You can put the docker file to the [deploy folder](https://github.com/youngmonkeys/ezyfox-server-archetype/tree/master/src/main/resources/archetype-resources/__rootArtifactId__-startup/deploy). You can take a look [create a project use ezyfox server guide](https://youngmonkeys.org/ezyfox-server/guides/create-ezyfox-server-project?lang=vi) to see how to the archetype work.

**Comment by trungdlp-wolffun** [comment]
@tvd12 thanks
