### ISSUE TITLE
The client no longer receives position data for a short period of time

### ISSUE THREAD

**Issue by Assambra** [youngmonkeys/ezyfox-server#129]
**Describe the bug**
I have strange behavior when I deploy the server and load it onto an external server and let it run. After about 10-15 seconds, the client will not receive any position data, but the server will continue to receive input data. I use the game box and can't log whether the error is that the messages are not being sent correctly or it's the server, e.g. due to packet drop/loss, firewall. No error message is output on the server and or client. 
The error does not occur when the server is tested in the IDE or on a local deployed Server on my PC.

**To Reproduce**
I don't know how to reproduce it, or what additional information will help to reproduce this behaviour

**Expected behavior**
The client should allways reseive position updates from the Server.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 10
- Works if runs the server locally in IDE IntellJ
- Works on locally deploy and run the server

**Smartphone (please complete the following information):**
- none information

**Server  (please complete the following information):**
- Hoster Hetzner
- Virtual machine on a proxmox Server Host
- OS Ubuntu 18.4.6 LTS
- Java: openjdk version "1.8.0_362"
- MongoDB

**Additional context**
Of course, it cannot be ruled out that it is the server or a setting from the host, for example. Firewall, incorrectly set route or something else. But I'm really confused as to where I can look for the error or how I can debug it.

**Comment by tvd12** [comment]
@Assambra could you give me your settings.xml file?

**Comment by Assambra** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<settings
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
          ezy-settings-1.0.0.xsd"
        xmlns="http://www.tvd12.com/schema/ezyfox/settings">

    <node-name>gs.assambra.com</node-name>
    <max-sessions>30000</max-sessions>

    <thread-pool-size>
        <statistics>1</statistics>
        <stream-handler>8</stream-handler>
        <socket-data-receiver>8</socket-data-receiver>
        <system-request-handler>8</system-request-handler>
        <extension-request-handler>8</extension-request-handler>
        <socket-disconnection-handler>2</socket-disconnection-handler>
        <socket-user-removal-handler>3</socket-user-removal-handler>
    </thread-pool-size>

    <streaming>
        <enable>true</enable>
    </streaming>

    <socket>
        <port>3005</port>
        <address>178.63.237.228</address>
        <active>true</active>
        <ssl-active>false</ssl-active>
        <ssl-type>CUSTOMIZATION</ssl-type>
        <ssl-handshake-timeout>300</ssl-handshake-timeout>
        <tcp-no-delay>true</tcp-no-delay>
        <max-request-size>4096</max-request-size>
        <writer-thread-pool-size>8</writer-thread-pool-size>
        <codec-creator>com.tvd12.ezyfox.codec.MsgPackCodecCreator</codec-creator>
    </socket>

    <udp>
        <port>2611</port>
        <address>178.63.237.228</address>
        <active>true</active>
        <max-request-size>1024</max-request-size>
        <channel-pool-size>8</channel-pool-size>
        <handler-thread-pool-size>5</handler-thread-pool-size>
    </udp>
	
    <administrators>
        <administrator>
            <username>admin</username>
            <password>admin</password>
            <access-token>admin</access-token>
        </administrator>
    </administrators>

    <session-management>
        <session-max-idle-time>60</session-max-idle-time>
        <session-max-waiting-time>30</session-max-waiting-time>
        <session-max-request-per-second>
            <value>200</value>
            <action>DISCONNECT_SESSION</action>
        </session-max-request-per-second>
    </session-management>

    <zones>
		<zone>
			<name>free-game-server</name>
			<config-file>free-game-server-zone-settings.xml</config-file>
			<active>true</active>
		</zone>
		<zone>
			<name>free-account-server</name>
			<config-file>free-account-server-zone-settings.xml</config-file>
			<active>true</active>
		</zone>
    </zones>

</settings>

**Comment by Assambra** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<settings
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
  		ezy-zone-settings-1.0.0.xsd"
        xmlns="http://www.tvd12.com/schema/ezyfox/settings">

    <max-users>10000</max-users>

    <streaming>
        <enable>true</enable>
    </streaming>

    <user-management>
        <allow-guest-login>true</allow-guest-login>
        <guest-name-prefix>Guest#</guest-name-prefix>
        <user-max-idle-time>30</user-max-idle-time>
        <max-session-per-user>15</max-session-per-user>
        <user-name-pattern>^[a-zA-Z0-9_.#]{3,64}$</user-name-pattern>
    </user-management>

    <applications>
        <application>
            <name>free-game-server</name>
            <folder>free-game-server-app-entry</folder>
            <entry-loader>com.assambra.game.app.AppEntryLoader</entry-loader>
            <config-file>config/config.properties</config-file>
        </application>
    </applications>

    <plugins>
        <plugin>
            <name>free-game-server</name>
            <folder>free-game-server-plugin</folder>
            <priority>-1</priority>
            <entry-loader>com.assambra.game.plugin.PluginEntryLoader</entry-loader>
            <config-file>config/config.properties</config-file>
            <listen-events>
                <event>USER_LOGIN</event>
                <event>USER_ADDED</event>
                <event>USER_REMOVED</event>
            </listen-events>
        </plugin>
    </plugins>
</settings>

**Comment by Assambra** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<settings
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.tvd12.com/schema/ezyfox/settings
  		ezy-zone-settings-1.0.0.xsd"
        xmlns="http://www.tvd12.com/schema/ezyfox/settings">

    <max-users>10000</max-users>

    <streaming>
        <enable>true</enable>
    </streaming>

    <user-management>
        <allow-guest-login>true</allow-guest-login>
        <guest-name-prefix>Guest#</guest-name-prefix>
        <user-max-idle-time>30</user-max-idle-time>
        <max-session-per-user>15</max-session-per-user>
        <user-name-pattern>^[a-zA-Z0-9_.#]{3,64}$</user-name-pattern>
    </user-management>

    <applications>
        <application>
            <name>free-account-server</name>
            <folder>free-account-server-app-entry</folder>
            <entry-loader>com.assambra.account.app.AppEntryLoader</entry-loader>
            <config-file>config/config.properties</config-file>
        </application>
    </applications>

    <plugins>
        <plugin>
            <name>free-account-server</name>
            <folder>free-account-server-plugin</folder>
            <priority>-1</priority>
            <entry-loader>com.assambra.account.plugin.PluginEntryLoader</entry-loader>
            <config-file>config/config.properties</config-file>
            <listen-events>
                <event>USER_LOGIN</event>
                <event>USER_ADDED</event>
                <event>USER_REMOVED</event>
            </listen-events>
        </plugin>
    </plugins>
</settings>

**Comment by tvd12** [comment]
`<address>178.63.237.228</address>` is a loopback address why don't you want use ``<address>0.0.0.0</address>`?

I see you have the repo: https://github.com/Assambra/Free-MMORPG are you asking for it?

**Comment by Assambra** [comment]
Yes it is for this repo, i insert the ip only for testing it accours with 0.0.0.0 too.

**Comment by tvd12** [comment]
@Assambra I haven't seen you create `MMORoom` and add MMOPlayer to `MMORoom`, could you show me?

**Comment by tvd12** [comment]
@Assambra could you change to this one:

```java
// class RoomService
 public void setPlayerPosition(MMOPlayer player, Vec3 nextPosition) {
        MMOGridRoom currentRoom = (MMOGridRoom) getCurrentRoom(player);
        currentRoom.setPlayerPosition(player, nextPosition);
        logger.info("near by players: {}", player.getNearbyPlayerNames());
    }
```

If you want to add more log, you can clone [game-box](https://github.com/youngmonkeys/game-box) and add more logs

**Comment by Assambra** [comment]
It does not log anything or more then before.

**Comment by tvd12** [comment]
it means `roomService.setPlayerPosition` wasn't called, may be client not send `playerInput` and `play` command could you check it?

**Comment by Assambra** [comment]
Play command should work it sends spawn command back to the user and inform all nearby clients to instantiate the characters/prefabs/Player model there wouldn't be visible without, and yesterday i enable a logger on Command it reseives input data. But in short i need more time to investigate, but its wired behaviour only on the live server not local...

**Comment by tvd12** [comment]
I run `free-game-server-startup/ClientTest` connect to `ClientTest` but I got `2023-10-20 17:56:54.625 [main] INFO  c.t.e.c.h.EzyDisconnectionHandler handle disconnection, reason: UNAUTHORIZED` maybe you need to give me an account

**Comment by Assambra** [comment]
Account: Musmacher 123456 or/and  Account Assambra 123456 but you are able to create a new account on ligin screen "need account?"

**Comment by tvd12** [comment]
How can I create my account? I'm not seeing on the README: https://github.com/Assambra/Free-MMORPG/tree/main

**Comment by Assambra** [comment]
![1](https://github.com/youngmonkeys/ezyfox-server/assets/6276777/a98d7a99-eb4b-442c-8fc1-582ed8fa262c)

**Comment by tvd12** [comment]
I mean what's web url?

I've just called play but nothing happen could you check log?

```java
package com.assambra.game.test;

import com.assambra.game.ApplicationStartup;
import com.assambra.game.app.constant.Commands;

import com.tvd12.ezyfox.core.constant.EzyResponseCommands;
import com.tvd12.ezyfox.entity.EzyArray;
import com.tvd12.ezyfox.entity.EzyData;
import com.tvd12.ezyfox.entity.EzyObject;
import com.tvd12.ezyfox.factory.EzyEntityFactory;
import com.tvd12.ezyfoxserver.client.EzyClient;
import com.tvd12.ezyfoxserver.client.EzyClients;
import com.tvd12.ezyfoxserver.client.EzyTcpClient;
import com.tvd12.ezyfoxserver.client.config.EzyClientConfig;
import com.tvd12.ezyfoxserver.client.constant.EzyCommand;
import com.tvd12.ezyfoxserver.client.entity.EzyApp;
import com.tvd12.ezyfoxserver.client.handler.EzyAppAccessHandler;
import com.tvd12.ezyfoxserver.client.handler.EzyHandshakeHandler;
import com.tvd12.ezyfoxserver.client.handler.EzyLoginSuccessHandler;
import com.tvd12.ezyfoxserver.client.request.EzyAppAccessRequest;
import com.tvd12.ezyfoxserver.client.request.EzyLoginRequest;
import com.tvd12.ezyfoxserver.client.request.EzyRequest;
import com.tvd12.ezyfoxserver.client.setup.EzyAppSetup;
import com.tvd12.ezyfoxserver.client.setup.EzySetup;
import com.tvd12.ezyfoxserver.client.socket.EzyMainEventsLoop;

public class ClientTest {

    public static void main(String[] args) {
        EzyClientConfig config = EzyClientConfig.builder()
            .zoneName(ApplicationStartup.ZONE_APP_NAME)
            .build();
        EzyClient client = new EzyTcpClient(config);
        setupClient(client);
        EzyClients.getInstance().addClient(client);
        client.connect("178.63.237.228", 3005);
        EzyMainEventsLoop mainEventsLoop = new EzyMainEventsLoop();
        mainEventsLoop.start(5);
    }

    public static void setupClient(EzyClient client) {
        EzySetup setup = client.setup();
        setup.addDataHandler(EzyCommand.HANDSHAKE, new EzyHandshakeHandler() {

            @Override
            protected EzyRequest getLoginRequest() {
                return new EzyLoginRequest(
                    ApplicationStartup.ZONE_APP_NAME,
                    "Assambra",
                    "123456"
                );
            }
        });
        setup.addDataHandler(EzyCommand.LOGIN, new EzyLoginSuccessHandler() {
            @Override
            protected void handleLoginSuccess(EzyData responseData) {
                client.send(new EzyAppAccessRequest(ApplicationStartup.ZONE_APP_NAME));
            }
        });
        setup.addDataHandler(EzyCommand.APP_ACCESS, new EzyAppAccessHandler() {
            @Override
            protected void postHandle(EzyApp app, EzyArray data) {
                app.send(Commands.HELLO, EzyEntityFactory.EMPTY_OBJECT);
                app.send(Commands.HELLO, EzyEntityFactory.newObjectBuilder()
                    .append("nickName", "Dzung")
                    .build());
                app.send(Commands.GO, EzyEntityFactory.EMPTY_OBJECT);
                app.send(Commands.GO, EzyEntityFactory.newObjectBuilder()
                    .append("nickName", "Dzung")
                    .build());
                app.send(
                    "createCharacter",
                    EzyEntityFactory.newObjectBuilder()
                        .append("name", "Dung")
                        .append("sex", "male")
                        .append("race", "test")
                        .append("model", "test")
                        .build()
                );
            }
        });

        EzyAppSetup appSetup = setup.setupApp(ApplicationStartup.ZONE_APP_NAME);
        appSetup.addDataHandler(EzyResponseCommands.ERROR, (app, data) -> {
            System.out.println("error: " + data);
        });
        appSetup.addDataHandler(Commands.HELLO, (app, data) -> {
            System.out.println("hello: " + data);
        });
        appSetup.addDataHandler(Commands.GO, (app, data) -> {
            System.out.println("hello: " + data);
        });
        appSetup.addDataHandler("characterList", (app, data) -> {
            System.out.println("characterList: " + data);
        });
        appSetup.addDataHandler("createCharacter", (app, data) -> {
            System.out.println("createCharacter: " + data);
            EzyObject objData = (EzyObject) data;
            app.send(
                "play",
                EzyEntityFactory
                    .newObjectBuilder()
                    .append("characterId", objData.get("characterId", Integer.class))
                    .build()
            );
        });
    }
}
```

**Comment by Assambra** [comment]
2023-10-20 11:13:22.374 [ezyfox-extension-request-handler-20-3] INFO  c.a.g.app.controller.GameController User Assambra try to cheat

**Comment by Assambra** [comment]
now you raise exceptions

**Comment by tvd12** [comment]
@Assambra for command play, if user has already played, I think you should return something like `gameId` to help user reconnect, my source code:

```java
package com.assambra.game.test;

import com.assambra.game.ApplicationStartup;
import com.assambra.game.app.constant.Commands;

import com.tvd12.ezyfox.core.constant.EzyResponseCommands;
import com.tvd12.ezyfox.entity.EzyArray;
import com.tvd12.ezyfox.entity.EzyData;
import com.tvd12.ezyfox.entity.EzyObject;
import com.tvd12.ezyfox.factory.EzyEntityFactory;
import com.tvd12.ezyfoxserver.client.EzyClient;
import com.tvd12.ezyfoxserver.client.EzyClients;
import com.tvd12.ezyfoxserver.client.EzyTcpClient;
import com.tvd12.ezyfoxserver.client.config.EzyClientConfig;
import com.tvd12.ezyfoxserver.client.constant.EzyCommand;
import com.tvd12.ezyfoxserver.client.entity.EzyApp;
import com.tvd12.ezyfoxserver.client.handler.EzyAppAccessHandler;
import com.tvd12.ezyfoxserver.client.handler.EzyHandshakeHandler;
import com.tvd12.ezyfoxserver.client.handler.EzyLoginSuccessHandler;
import com.tvd12.ezyfoxserver.client.request.EzyAppAccessRequest;
import com.tvd12.ezyfoxserver.client.request.EzyLoginRequest;
import com.tvd12.ezyfoxserver.client.request.EzyRequest;
import com.tvd12.ezyfoxserver.client.setup.EzyAppSetup;
import com.tvd12.ezyfoxserver.client.setup.EzySetup;
import com.tvd12.ezyfoxserver.client.socket.EzyMainEventsLoop;

public class ClientTest {

    public static void main(String[] args) {
        EzyClientConfig config = EzyClientConfig.builder()
            .zoneName(ApplicationStartup.ZONE_APP_NAME)
            .build();
        EzyClient client = new EzyTcpClient(config);
        setupClient(client);
        EzyClients.getInstance().addClient(client);
        client.connect("178.63.237.228", 3005);
        EzyMainEventsLoop mainEventsLoop = new EzyMainEventsLoop();
        mainEventsLoop.start(5);
    }

    public static void setupClient(EzyClient client) {
        EzySetup setup = client.setup();
        setup.addDataHandler(EzyCommand.HANDSHAKE, new EzyHandshakeHandler() {

            @Override
            protected EzyRequest getLoginRequest() {
                return new EzyLoginRequest(
                    ApplicationStartup.ZONE_APP_NAME,
                    "Assambra",
                    "123456"
                );
            }
        });
        setup.addDataHandler(EzyCommand.LOGIN, new EzyLoginSuccessHandler() {
            @Override
            protected void handleLoginSuccess(EzyData responseData) {
                client.send(new EzyAppAccessRequest(ApplicationStartup.ZONE_APP_NAME));
            }
        });
        setup.addDataHandler(EzyCommand.APP_ACCESS, new EzyAppAccessHandler() {
            @Override
            protected void postHandle(EzyApp app, EzyArray data) {
                app.send(Commands.HELLO, EzyEntityFactory.EMPTY_OBJECT);
                app.send(Commands.HELLO, EzyEntityFactory.newObjectBuilder()
                    .append("nickName", "Dzung")
                    .build());
                app.send(Commands.GO, EzyEntityFactory.EMPTY_OBJECT);
                app.send(Commands.GO, EzyEntityFactory.newObjectBuilder()
                    .append("nickName", "Dzung")
                    .build());
                app.send(
                    "createCharacter",
                    EzyEntityFactory.newObjectBuilder()
                        .append("name", "Dung")
                        .append("sex", "male")
                        .append("race", "test")
                        .append("model", "test")
                        .build()
                );
            }
        });

        EzyAppSetup appSetup = setup.setupApp(ApplicationStartup.ZONE_APP_NAME);
        appSetup.addDataHandler(EzyResponseCommands.ERROR, (app, data) -> {
            System.out.println("error: " + data);
        });
        appSetup.addDataHandler(Commands.HELLO, (app, data) -> {
            System.out.println("hello: " + data);
        });
        appSetup.addDataHandler(Commands.GO, (app, data) -> {
            System.out.println("hello: " + data);
        });
        appSetup.addDataHandler("characterList", (app, data) -> {
//            System.out.println("characterList: " + data);
            EzyArray characterList = (EzyArray) data;
            if (characterList.size() > 0) {
                System.out.println("start to play");
                app.send(
                    "play",
                    EzyEntityFactory
                        .newObjectBuilder()
                        .append(
                            "characterId",
                            characterList
                                .get(0, EzyArray.class)
                                .get(0, Integer.class))
                        .build()
                );
            }
        });
        appSetup.addDataHandler("createCharacter", (app, data) -> {
            System.out.println("createCharacter: " + data);
            EzyObject objData = (EzyObject) data;
            String result = objData.get("result");
            if ("name_already_in_use".equals(result)) {
                app.send("characterList");
            } else {
                app.send(
                    "play",
                    EzyEntityFactory
                        .newObjectBuilder()
                        .append("characterId", objData.get("characterId", Integer.class))
                        .build()
                );
            }
        });
        appSetup.addDataHandler("play", (app, data) -> {
            System.out.println("play: " + data);
        });
    }
}

```

**Comment by Assambra** [comment]
"I mean what's web url?" do you mean websocket if yes it isnt enabled else it should be gs.assambra.com

**Comment by Assambra** [comment]
I have another problem on the NetworkManagerAccount it happends one time on start is this a timing problem should i create a coroutine to wait some milli sec and set a boolean to true after that it runs nomaly the processEvents() in update? 


private void Update()
    {
        EzyClients.getInstance()
            .getClient(socketConfigVariable.Value.ZoneName)
            .processEvents();
    }


InvalidCastException: Specified cast is not valid.
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)

com.tvd12.ezyfoxserver.client.support.EzySocketProxy+<>c__DisplayClass52_0`1[T].<onAppAccessed>b__0 (com.tvd12.ezyfoxserver.client.support.EzyAppProxy appProxy, System.Object data) (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/support/EzySocketProxy.cs:271)
com.tvd12.ezyfoxserver.client.support.EzySocketProxy+AppAccessHandler.postHandle (com.tvd12.ezyfoxserver.client.entity.EzyApp app, com.tvd12.ezyfoxserver.client.entity.EzyArray appData) (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/support/EzySocketProxy.cs:483)
com.tvd12.ezyfoxserver.client.handler.EzyAppAccessHandler.handle (com.tvd12.ezyfoxserver.client.entity.EzyArray data) (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/handler/EzyAppAccessHandler.cs:16)
com.tvd12.ezyfoxserver.client.handler.EzyDataHandlers.handle (com.tvd12.ezyfoxserver.client.constant.EzyCommand cmd, com.tvd12.ezyfoxserver.client.entity.EzyArray data) (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/handler/EzyDataHandlers.cs:36)
com.tvd12.ezyfoxserver.client.socket.EzySocketClient.processReceivedMessage (com.tvd12.ezyfoxserver.client.entity.EzyArray message) (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/socket/EzySocketClient.cs:336)
com.tvd12.ezyfoxserver.client.socket.EzySocketClient.processReceivedMessages0 () (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/socket/EzySocketClient.cs:308)
com.tvd12.ezyfoxserver.client.socket.EzySocketClient.processReceivedMessages () (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/socket/EzySocketClient.cs:280)
com.tvd12.ezyfoxserver.client.socket.EzySocketClient.processEventMessages () (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/socket/EzySocketClient.cs:224)
com.tvd12.ezyfoxserver.client.EzyTcpClient.processEvents () (at Assets/Free-Client/Plugins/ezyfox-server-csharp-client-unity-client/EzyTcpClient.cs:192)
NetworkManagerAccount.Update () (at Assets/Free-Client/Scripts/Managers/NetworkManagerAccount.cs:40)

**Comment by tvd12** [comment]
@Assambra Could you resolve by your self or need my help?

**Comment by Assambra** [comment]
this is another error in need help with. The main issue i still there too i try now to get information and log every step and hope to find the issue.

**Comment by tvd12** [comment]
@Assambra could you change https://github.com/Assambra/Free-MMORPG/blob/main/Free-Client/Assets/Free-Client/Scripts/Managers/NetworkManagerGame.cs#L65-L67 to:

```cs
OnLoginSuccess<Object>(OnLoginSucess);
OnLoginError<Object>(OnLoginError);
OnAppAccessed<EzyArray>(OnAppAccessed);
```

The error log report error here: https://github.com/youngmonkeys/ezyfox-server-csharp-client/blob/master/support/EzySocketProxy.cs#L271 could you place a breakpoint?

**Comment by Assambra** [comment]
Excuse me, is the logger disabled by default or some value in settings? On the deploy the server no logger.info() are shown. Thats the reason from earlyer i dont get any logs as you ask for.

**Comment by tvd12** [comment]
@Assambra are you running by free-game-server-startup or you download ezyfox-server and run?

**Comment by tvd12** [comment]
Ah you have `settings.xml` so I guess you're running by `ezyfox-server` could you give me your `logback.xml` file?

**Comment by Assambra** [comment]
@tvd12  do you mean the main issue or now with the logger?

Logger issue: it works only on IDE IntellJ with startup but not in the downloaded deployed servers local and remote.

Main issue: 
both of them i descriped in the main issue on top, it works on local server with the downloaded server and deployed server also in the IDE with startup, but not on the remote server  if i upload it there it stops client to send positions data after amount of time.

**Comment by Assambra** [comment]
<configuration>
    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>
                %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="fileRolling" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/ezyfox-server.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logs/ezyfox-server.log.%d{yyyy-MM-dd}</fileNamePattern>
        </rollingPolicy>
        <encoder>
            <pattern>
                %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="file" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="fileRolling" />
    </appender>


    <root level="info">
        <appender-ref ref="console"/>
        <appender-ref ref="file"/>
    </root>
</configuration>

**Comment by tvd12** [comment]
@Assambra I mean logger. Are you running on ubuntu by rung `./console.sh` or `./start-service.sh ; tail -f logs/ezyfox-server.log`?

I'm thinking to support you directly by using https://anydesk.com/en by try to use github issue first

**Comment by Assambra** [comment]
Excuse me i dont wanted to messy up your git hub issues :(

yes,  ./console.sh and on windows batch file console.bat

do you have some alias to invite you?

**Comment by Assambra** [comment]
Ok i found now a solution that dont breaks position updates after time but i dont happy with it because i want use udp for position updates because its faster and smaller messages. 

I dont now why it happends only if i have enabled useUdp.

**Comment by tvd12** [comment]
Let us continue via discord
