### ISSUE TITLE
build-issue: niocodec missing dependency

### ISSUE THREAD

**Issue by communityus** [youngmonkeys/ezyfox-server#36]
mvn clean install -U -Dmaven.test.skip=true -f ezyfox-server-niorunner
(tried with and without -U)

impacts > /ezyfox-server-support/ build also

**Comment by communityus** [comment]
errors: ezyfox-server-niorunner (referencing **ezfox-server-niocodec**)

~/git/ezy/ezyfox-server $ mvn clean install -U -Dmaven.test.skip=true -f ezyfox-server-niorunner
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.tvd12:ezyfox-server-niorunner >------------------
[INFO] Building ezyfox-server-niorunner 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/tvd12/ezyfox-server-niocodec/1.0.0/ezyfox-server-niocodec-1.0.0.pom
[WARNING] The POM for com.tvd12:ezyfox-server-niocodec:jar:1.0.0 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/tvd12/ezyfox-server-niocodec/1.0.0/ezyfox-server-niocodec-1.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.505 s
[INFO] Finished at: 2018-10-12T18:41:42-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ezyfox-server-niorunner: Could not resolve dependencies for project com.tvd12:ezyfox-server-niorunner:jar:1.0.0: Could not find artifact com.tvd12:ezyfox-server-niocodec:jar:1.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by communityus** [comment]
errors: ezyfox-server-support (referencing **ezyfox-server-niorunner**)

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.tvd12:ezyfox-server-support >-------------------
[INFO] Building ezyfox-server-support 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/tvd12/ezyfox-core/2.0.0/ezyfox-core-2.0.0.pom
[WARNING] The POM for com.tvd12:ezyfox-core:jar:2.0.0 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/com/tvd12/ezyfox-core/2.0.0/ezyfox-core-2.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.827 s
[INFO] Finished at: 2018-10-12T18:53:25-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ezyfox-server-support: Could not resolve dependencies for project com.tvd12:ezyfox-server-support:jar:1.0.0: Could not find artifact com.tvd12:ezyfox-core:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tvd12** [comment]
fixed in commit [95aac7](https://github.com/youngmonkeys/ezyfox-server/commit/95aac70194f8da8962c4fa25e828940c3c0761ad)
